class UrlConstants:
    FETCH_ALL_RECORDS = '/fetchAllRecords'
    POST = 'POST'
    GET = 'GET'
    DELETE = 'DELETE'
    PUT = 'PUT'
    DATABASE_URL = "mongodb+srv://root:srinivas1994@cluster0.4ta2g.mongodb.net/user_details_db?retryWrites=true&w=majority"
    USER_DETAILS = '/userDetails'
    Id = 'Id:'
    firstName = 'fistName:'
    lastName = 'lastName:'
    MYEMAIL = 'mssrinivas7@gmail.com'
    MOBILE = 'mobile'
    EMAIL_ADDRESS = 'email_address'
    PASSWORD = 'password'
    CHECK_EMAIL_ID = '/EmailIdCheck/<string:email_address>'
    ResponseText = 'ResponseText'
    MAIL_ID_EXITS = 'Mail id is exits'
    MAIL_ID_NOT_EXITS = 'Mail id is Not exits'
    CHECK_LOGIN_CREDENTIALS = '/checkUserCredentials/<string:email_address>/<string:user_password>'
