class UrlConstants:
    FETCH_ALL_RECORDS = '/fetchAllRecords'
    POST = 'POST'
    GET = 'GET'
    DELETE = 'DELETE'
    PUT = 'PUT'
    DATABASE_URL = 'mysql://root:password@34.93.156.24:3306/user_details_db'
    USER_DETAILS = '/userDetails'
    Id = 'Id:'
    firstName = 'fistName:'
    lastName = 'lastName:'
    MYEMAIL = 'mssrinivas7@gmail.com'
    MOBILE = 'mobile'
    EMAIL_ADDRESS = 'email_address'
    PASSWORD = 'password'
